server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:orders}
    password: ${SPRING_DATASOURCE_PASSWORD:orders}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

inventory:
  client:
    base-url: ${INVENTORY_BASE_URL:http://localhost:8081}
    timeout: PT5S

logging:
  level:
    org.springframework.web: INFO
